# Generated by Django 5.2.8 on 2025-12-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_spots_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kebabspot',
            old_name='location',
            new_name='coordinates',
        ),
    ]
