# Generated by Django 5.2.8 on 2025-12-09 17:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_spots_app', '0002_rename_location_kebabspot_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebabspot',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
