# Generated by Django 5.2.8 on 2026-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_spots_app', '0003_alter_kebabspot_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebabspot',
            name='benches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='car_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='fire_pit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='fishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='gazebos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='near_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='private_territory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='shop_nearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kebabspot',
            name='trash_cans',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kebabspot',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
