# Generated by Django 5.2.8 on 2026-01-13 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab_spots_app', '0005_rename_rating_kebabspot_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kebabspotrating',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
